### ISSUE TITLE
Issue with GLPK loading in Cameo

### ISSUE THREAD

**Issue by ThierryMondeel** [biosustain/cameo#46] opened 2016-02-19 17:08 UTC
Hi all,

I have been getting an error upon loading cameo about optlang not having solvers installed and missing the glpk interface. When executing "import cameo" I get
> ERROR:optlang:No solvers available.
> AttributeError: 'module' object has no attribute 'glpk_interface'

My guess is this has happened since some upgrade recently because a while back Cameo was working fine. I tried regular install through pip with a --pre flag and also using the requirements.txt files but no luck. I do have GLPK installed on my Mac and cobrapy is working as it should. 

After looking at the installation output from pip i noticed that swiglpk failed at building the wheel and then installed through setup.py correctly. With wheel I get the error

> You are attempting to install a package to a directory that is not
  on PYTHONPATH and which Python does not read ".pth" files from.  The
  installation directory you specified (via --install-dir, --prefix, or
  the distutils default setting) was:
   build/bdist.macosx-10.5-x86_64/wheel/

I will take a look at the suggested fixes. But this seems abnormal to me, any ideas on a fix?

**Comment by phantomas1234** [comment] 2016-02-19 20:00
Hi Thierry, I am happy that you're giving cameo a try (have you been using it for a while?)! I am not so happy that you ended up with this problem. Can you check if your problem is gone if you upgrade swiglpk via `pip install swiglpk --upgrade`? It should install swiglpk==1.2.12 and this annoying issue https://github.com/biosustain/swiglpk/issues/8 with bdist_wheel that I think is the reason behind your troubles too should be gone.

**Comment by ThierryMondeel** [comment] 2016-02-19 22:32
Hi Nik,

I played around with it for a while after meeting/talking to you in Heidelberg (if I remember correctly) and I like what you guys did! But after a few months of focusing on other projects I suddenly ran into this issue. 
You are right though when I ran the upgrade command to 1.2.12 the install suddenly worked with bdist_wheel. Unfortunately, this does not seem to solve my issue as I still cannot import cameo.

I do indeed now have swiglpk in the 1.2.12 version:
| =>  pip show swiglpk
---
Metadata-Version: 2.0
Name: swiglpk
Hi Nik
Version: 1.2.12
Summary: swiglpk - Simple swig bindings for the GNU Linear Programming Kit

But when running: 
> from cameo import *

> No solvers available.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/thierry/anaconda/envs/python3/lib/python3.5/site-packages/cameo/__init__.py", line 69, in <module>
>     from cameo.io import load_model
>   File "/Users/thierry/anaconda/envs/python3/lib/python3.5/site-packages/cameo/io.py", line 31, in <module>
>     def load_model(path_or_handle, solver_interface=optlang.glpk_interface, sanitize=True):
> AttributeError: module 'optlang' has no attribute 'glpk_interface'

So it looks like a GLPK issue, but the weird thing is cobrapy by itself is working.

Thanks for the help!

**Comment by KristianJensen** [comment] 2016-02-20 12:39
Hi Thierry.

The issue you're experiencing is caused by failure to import swiglpk. I have previously solved this by uninstalling swiglpk and glpk, and then reinstalling glpk and swiglpk (in that order). If this doesn't solve it try running 'import swiglpk' and post the error traceback here.

Best, Kristian

**Comment by ThierryMondeel** [comment] 2016-02-21 20:55
Hi Kristian, 

Per your suggestion I uninstall swiglpk, reinstalled glpk through homebrew, also reinstall swig, then reinstalled swiglpk through pip. See error log below:
> import swiglpk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thierry/anaconda/lib/python2.7/site-packages/swiglpk.py", line 28, in <module>
    _swiglpk = swig_import_helper()
  File "/Users/thierry/anaconda/lib/python2.7/site-packages/swiglpk.py", line 24, in swig_import_helper
    _mod = imp.load_module('_swiglpk', fp, pathname, description)
ImportError: dlopen(/Users/thierry/anaconda/lib/python2.7/site-packages/_swiglpk.so, 2): Symbol not found: __glp_lpx_add_cols
  Referenced from: /Users/thierry/anaconda/lib/python2.7/site-packages/_swiglpk.so
  Expected in: flat namespace
 in /Users/thierry/anaconda/lib/python2.7/site-packages/_swiglpk.so

**Comment by KristianJensen** [comment] 2016-02-23 14:28
What version of Python are you running? And did you recently change Python version?
Try making a new conda environment: "conda create -n test_env python=2.7.9 swiglpk"
and then
"source activate test_env"
"python -c 'import swiglpk' "

You can also try doing the same with python=3.4

**Comment by ThierryMondeel** [comment] 2016-03-10 15:48
Hi Kristian,

Sorry for the delayed response. Thanks for the suggestion, you may have been right but the problem solved itself: I switched to a new macbook a week ago and the install went flawlessly. 

Thanks for all help!

**Comment by phantomas1234** [comment] 2016-03-30 15:24
I am closing this then

**Closed by phantomas1234** 2016-03-30 15:24 UTC
Labels: bug
